config/routes.rb
Rails.application.routes.draw do
  root 'people#index'
  resources :people

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  # validates :name, :age, :gender, presence: true
  # validates :name, uniquness: true   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
    #people represents both classes in that array
    # binding.pry
  end

  def show
    @person = Person.find(params[:id])
    #@person
    #shows certain person's information
  end

  def new
    @people = Person.new
  end

  def edit

  end

  def create
  end
  
  def update
  end
  
  def destroy
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsModels</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/edit.html.erb
<h1>People#edit</h1>
<p>Find me in app/views/people/edit.html.erb</p>

app/views/people/index.html.erb
<h1>List of Amazing People</h1>
<hr />

<h1> People </h1>
<% @people.each do |person| %>
  <h2><%= person.name %></h2>
  <%= link_to 'Show person', person_path(person) %>
  <% end %>

  <!--person means the current person and class we're working with


<!-- erb tags to use ruby
 loop through list of people. 
 each 

app/views/people/new.html.erb
<h1> New Person </h1>
<%= form_for @person do |f| %>
  <%= f.label :name %>:
  <%= f.label :age %>:
  <%= f.label :hair_color %>:
  <%= f.label :eye_color %>:
  <%= f.label :gender %>:
  <%= f.label :alive %>:
  <%= f.submit %>
  <%= end %>

app/views/people/show.html.erb
<h1> Person </h1>
<h2><%= @person.name %></h2>
  <h3><%= @person.age %></h3>
  <h4><%= @person.hair_color %></h4>
  <h5><%= @person.eye_color %></h5>
  <h6><%= @person.gender %></h6>
  <h7><%= @person.alive %></h7>
  <%= link_to 'back', people_path %>
  